# Generated by rust2rpm 27
%bcond check 0
%global debug_package %{nil}

%global crate hostname

Name:           rust-hostname
Version:        0.4.1
Release:        %autorelease
Summary:        Cross-platform system's host name functions

License:        MIT
URL:            https://crates.io/crates/hostname
Source:         %{crates_source}
# Automatically generated patch to strip dependencies and normalize metadata
Patch:          hostname-fix-metadata-auto.diff

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
Cross-platform system's host name functions.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/LICENSE
%doc %{crate_instdir}/CHANGELOG.md
%doc %{crate_instdir}/README.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+set-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+set-devel %{_description}

This package contains library source intended for building other packages which
use the "set" feature of the "%{crate}" crate.

%files       -n %{name}+set-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
%autochangelog
