# Generated by rust2rpm 27
%bcond check 0
%global debug_package %{nil}

%global crate ssh-agent
%define commit 802b94ccf2e00ac33a3863300d0769f02b62d807

Name:           rust-ssh-agent
Version:        0.2.3
Release:        %autorelease
Summary:        Library for implementing an SSH agent

License:        MIT
URL:            https://crates.io/crates/ssh-agent
Source:         https://github.com/z4yx/ssh-agent.rs/archive/%{commit}.tar.gz

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
Library for implementing an SSH agent.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/LICENSE
%doc %{crate_instdir}/README.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+agent-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+agent-devel %{_description}

This package contains library source intended for building other packages which
use the "agent" feature of the "%{crate}" crate.

%files       -n %{name}+agent-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+bytes-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+bytes-devel %{_description}

This package contains library source intended for building other packages which
use the "bytes" feature of the "%{crate}" crate.

%files       -n %{name}+bytes-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+tokio-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+tokio-devel %{_description}

This package contains library source intended for building other packages which
use the "tokio" feature of the "%{crate}" crate.

%files       -n %{name}+tokio-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+tokio-uds-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+tokio-uds-devel %{_description}

This package contains library source intended for building other packages which
use the "tokio-uds" feature of the "%{crate}" crate.

%files       -n %{name}+tokio-uds-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
%autosetup -n %{crate}.rs-%{commit} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
%autochangelog
