name: Weekly sync

on:
  workflow_dispatch:
  schedule:
  - cron: '0 0 * * 1'

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - run: |
        apt -y update && apt -y install rpm
        pip install -r requirements.txt
    - name: Sync packages
      run: |
        git config --local user.name "github-actions[bot]"
        git config --local user.email "enchufa2@users.noreply.github.com"
        mkdir -p $HOME/.config && echo "$COPR_TOKEN" > $HOME/.config/copr
        python sync.py
      env:
        COPR_TOKEN: ${{ secrets.COPR_TOKEN }}
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
