name: Daily sync

on:
  workflow_dispatch:
  schedule:
  - cron: '0 0 * * *'

jobs:
  sync:
    runs-on: ubuntu-latest
    container: fedora:rawhide
    steps:
    - name: Setup
      run: dnf -y install git-core rpm-build python3-copr python3-PyGithub
    - uses: actions/checkout@v3
    - name: Sync packages
      run: |
        git config --global --add safe.directory "$GITHUB_WORKSPACE"
        git config --local user.name "github-actions[bot]"
        git config --local user.email "enchufa2@users.noreply.github.com"
        mkdir -p $HOME/.config && echo "$TOKEN" > $HOME/.config/copr
        ./sync.py
      env:
        TOKEN: ${{ secrets.COPR_TOKEN }}
