name: Daily sync

on:
  workflow_dispatch:
  schedule:
  - cron: '0 0 * * *'

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    - name: Set up Python
      uses: actions/setup-python@v4
    - name: Configuration
      run: |
        git config --local user.name "Github Action"
        git config --local user.email "enchufa2@users.noreply.github.com"
        sudo apt-get update -y && sudo apt-get install -y libkrb5-dev rpm
        mkdir -p $HOME/.config && echo "$TOKEN" > $HOME/.config/copr
        python -m pip install --upgrade pip
        pip install copr PyGithub GitPython
      env:
        TOKEN: ${{ secrets.COPR_TOKEN }}
    - name: Sync packages
      run: ./sync.py
