name: Daily sync

on:
  workflow_dispatch:
  schedule:
  - cron: '0 0 * * *'

jobs:
  sync:
    runs-on: ubuntu-latest
    container: fedora:rawhide
    steps:
    - name: Setup
      run: |
        dnf -y install git-core rpm-build python3-copr python3-PyGithub
        git config --local user.name "Github Action"
        git config --local user.email "enchufa2@users.noreply.github.com"
        mkdir -p $HOME/.config && echo "$TOKEN" > $HOME/.config/copr
      env:
        TOKEN: ${{ secrets.COPR_TOKEN }}
    - uses: actions/checkout@v3
    - name: Sync packages
      run: ./sync.py
